### ISSUE TITLE
Missing svg tag and subtags

### ISSUE THREAD

**Issue by Tmpod** [ScottPierce/kotlin-html#16]
Hey there again! I'm back with another collection of missing tags. You mentioned something about the generator, but I didn't get how it works, specially for a tag like svg, which has some sub components to it.

**Comment by ScottPierce** [comment]
So basically, the way the project is structured - everything in [this gradle module](https://github.com/ScottPierce/kotlin-html/tree/master/kotlin-html-generator) is responsible for generating all the code in [this folder of the main project](https://github.com/ScottPierce/kotlin-html/tree/master/kotlin-html/src/genMain/kotlin/dev/scottpierce/html), which is where 90% of the code lives. Basically 90% of the code for this project is written / generated by the code generator project I linked above.

I tried to write an SVG tag at one point actually. It ended up being way more work than it's worth. At the end of the day - you want to copy and paste an SVG into your project, not create one on the fly, using this project, right? I recommend creating SVG functions for that like this, by copying and pasting the SVGs

## SVG Functions
```Kotlin
fun BodyContext.caretDown(width: Dimension = 0.8.em, height: Dimension = 0.8.em) {
    +("<svg width=\"$width\" height=\"$height\" viewBox=\"0 0 1792 1792\">" +
            "<path d=\"M1408 704q0 26-19 45l-448 448q-19 19-45 19t-45-19l-448-448q-19-19-19-45t19-45 " +
            "45-19h896q26 0 45 19t19 45z\"/></svg>")
}

fun BodyContext.ic_phone() {
    +("<svg style=\"width: 1.1rem; height: 1.1rem; flex-grow: 0;\" version=\"1.1\" viewBox=\"0 0 18 18\">" +
            "<g fill=\"none\" fill-rule=\"evenodd\" id=\"Page-1\" stroke=\"none\" stroke-width=\"1\">" +
            "<g fill=\"#FFFFFF\" id=\"Icons-Communication\" transform=\"translate(-85.000000, -126.000000)\">" +
            "<g id=\"phone\" transform=\"translate(85.000000, 126.000000)\">" +
            "<path d=\"M3.6,7.8 C5,10.6 7.4,12.9 10.2,14.4 L12.4,12.2 C12.7,11.9 13.1,11.8 13.4,12 C14.5,12.4 " +
            "15.7,12.6 17,12.6 C17.6,12.6 18,13 18,13.6 L18,17 C18,17.6 17.6,18 17,18 C7.6,18 0,10.4 0,1 C0,0.4 " +
            "0.4,0 1,0 L4.5,0 C5.1,0 5.5,0.4 5.5,1 C5.5,2.2 5.7,3.4 6.1,4.6 C6.2,4.9 6.1,5.3 5.9,5.6 L3.6,7.8 " +
            "L3.6,7.8 Z\" id=\"Shape\"></path></g></g></g></svg>")
}
```

And then you can include the svg in your html like this:
```Kotlin
StringBuilderHtmlWriter().html { 
    body { 
        span { 
            +"Phone Icon:"
            ic_phone()
        }
    }
}
```

## Inlining SVG Files
I think you only need to use the above aproach though if you want to provide function params to alter the svg. Otherwise you could also use the `inlineFile` function:
```Kotlin
StringBuilderHtmlWriter().html {
    body {
        span {
            +"Phone Icon:"
            inlineFile(File("<file path to phone svg>"))
        }
    }
}
```

**Comment by Tmpod** [comment]
Ooh I see now! Seems super nice ngl. And ye, your suggestion of using functions for the SVG sounds ok ig.
Btw, what about adding CSS stuff? Like, new units (`vh` for example) or new attributes.

**Comment by ScottPierce** [comment]
CSS is also generated. To add a property, you just add an enum value here, run the generator, check it all in and make a PR: 
https://github.com/ScottPierce/kotlin-html/blob/master/kotlin-html-generator/src/main/kotlin/dev/scottpierce/html/generate/model/StyleProperty.kt#L12-L78

Css is probably where the lib is most likely missing features that you want. There were a few traits where there were so many different forms of defining it, I found it difficult to create a nice API. It's something I plan to revisit in the future.

 FYI - I'm in the process of re-writing some of the base CSS code - so there may be some breaking changes there. It won't be too bad though, and if you are only using basic features, there is a good chance nothing will change for you.

The main problem that I'm trying to fix is that supporting media queries in CSS is a nightmare. Everything gets all spread out, where your definition for single style ends up in 4 different places. And when we have a library like this, that's something the library can handle for us.

I'm trying to create something like this:
```Kotlin
styleSheet {
  style(".container") {
    background = color("#333333")
    tablet {
      background = color("#222222")
    }
    phone {
       background = color("#333333")
    }
  }
}
```

**Comment by Tmpod** [comment]
Ye, currently I'm not using any more complex features, but an interface like that would be really neat.
I'm gonna attempt to add some stuff to HTML and CSS and open a PR. 
Thanks for the help!
